version: "3"

networks:
  vpn-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.1

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2022.07.1
    environment:
      WEBPASSWORD: 'password'
      # https://docs.pi-hole.net/guides/dns/upstream-dns-providers/#cloudflare-dns
      PIHOLE_DNS_: '1.1.1.1;1.0.0.1;2606:4700:4700::1111;2606:4700:4700::1001'
      QUERY_LOGGING: 'true'
    volumes:
      - .config/pihole:/etc/pihole
      - .config/dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      vpn-network:
        ipv4_address: 172.16.0.2
  caddy:
    image: caddy:2.4.6-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - .data/caddy:/data
    networks:
      vpn-network:
        ipv4_address: 172.16.0.3
    ports:
      - "443:443"
      - "80:80"
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      # - PEERS=4
      - PEERDNS=172.16.0.2
    volumes:
      - .config/wireguard:/config
      - /lib/modules:/lib/modules
      - /usr/src:/usr/src
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      vpn-network:
        ipv4_address: 172.16.0.9
